replicaCount: 1

image:
  repository: jonasbraganca/simple-website
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  hostname: simple-website.local
