apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-website
  labels:
    desafio: jackexperts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-website
      desafio: jackexperts
  template:
    metadata:
      labels:
        app: simple-website
    spec:
      containers:
      - name: simple-website
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-config-volume
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: website-config-volume
        configMap:
          name: website-config

