apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-website
  labels:
    app: simple-website
    desafio: jackexperts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-website
  template:
    metadata:
      labels:
        app: simple-website
        desafio: jackexperts
    spec:
      containers:
      - name: nginx
        image: jonasbraganca/simple-website:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: website-content
        configMap:
          name: website-config


