apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-website

  template:
    metadata:
      labels:
        app: simple-website
    spec:
      containers:
      - name: simple-website
        image: jonasbraganca/simple-website:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-config-volume
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: website-config-volume
        configMap:
          name: website-config

