name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Minikube
      run: |
        sudo apt-get update -y
        sudo apt-get install -y curl apt-transport-https
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        
    - name: Start Minikube
      run: |
        minikube start --driver=docker
        minikube status

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t jonasbraganca/simple-website:latest .

    - name: Deploy with Helm
      run: |
        helm repo add stable https://charts.helm.sh/stable
        helm upgrade --install simple-website ./helm-chart \
          --set image.repository=jonasbraganca/simple-website \
          --set image.tag=latest

    - name: Get Pods
      run: |
        kubectl get pods
