name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Constrói a imagem localmente (sem fazer push para o Docker Hub)
    - name: Build Docker image
      run: |
        docker build -t jonasbraganca/simple-website:latest .

    # Instala o Helm e realiza o deploy da aplicação no Minikube
    - name: Deploy with Helm
      run: |
        helm upgrade --install simple-website ./helm-chart \
          --set image.repository=jonasbraganca/simple-website \
          --set image.tag=latest
